added cyc id in account setting modal
fgacyc/erp pull request #14
Opened 2023-08-10 14:34 UTC by xylim98

### Please tell us what you did
    1. Added CYC ID in UI_SettingModalLeft.jsx
    2. Added CYC ID in SettingModalAccount.jsx
    3.
    4.

### Are there any concerns that may be raised ?
FYI, I am pointing to dev branch correct?

### Please add which issue does this PR close below using ("closes #issue_number")

2023-08-10 14:46 UTC, ETCasual commented
Hi sorry just checking did @Dorothea303  assigned u on this?

2023-08-10 14:51 UTC, xylim98 commented
Nope, I self-asign since @yuenci description seems to be clear and straight forward

2023-08-10 14:57 UTC, ETCasual commented
Oh ok cuz right now we are almost done with migrating from JavaScript to TypeScript, so to push new changes to the code would need to wait for the task to be completed as it would introduce breaking changes to the code

Ill merge this when the migration task is done

2023-08-10 15:00 UTC, xylim98 commented
oh i c, ok.

2023-08-12 05:38 UTC, ETCasual commented
@xylim98  can u rewrite ur components into `.tsx` variants? Then ill review and merge it

2023-08-13 14:43 UTC, ETCasual requested changes
Use **Logical OR** instead of `&&` so there is a default value like "-" when the API does not return this field in the data so it doesnt just dissapear

2023-08-13 14:43 UTC, ETCasual commented on src/components/UI_Modal/UI_SettingModal/SettingModalPages/SettingModalAccount.tsx
> +						<div className="setting-desc-text-grey">{cyc_id && cyc_id}</div>
can we use a **Logical OR operator** `||` with a default value at the back like "-" instead of `&&` for this? so it wont be empty when the api didnt return data for this field

2023-08-13 14:43 UTC, ETCasual commented on src/components/UI_Modal/UI_SettingModal/UI_SettingModalLeft.tsx
> +							{username && username}
can we use a **Logical OR operator** `||` with a default value at the back like "-" instead of `&&` for this? so it wont be empty when the api didnt return data for this field

2023-08-13 14:43 UTC, ETCasual commented on src/components/UI_Modal/UI_SettingModal/UI_SettingModalLeft.tsx
> +							{cyc_id && cyc_id}
can we use a **Logical OR operator** `||` with a default value at the back like "-" instead of `&&` for this? so it wont be empty when the api didnt return data for this field

2023-08-14 15:18 UTC, ETCasual commented
Yup yup, just need to change the `logical and` with `logical or` then its good to go

2023-08-14 15:20 UTC, xylim98 commented on src/components/UI_Modal/UI_SettingModal/SettingModalPages/SettingModalAccount.tsx
> +						<div className="setting-desc-text-grey">{cyc_id && cyc_id}</div>
I actually intentionally follow the previous author coding style.

In that case, I think [Nullish Coalescing Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) would be more suitable.

2023-08-14 15:24 UTC, ETCasual commented on src/components/UI_Modal/UI_SettingModal/SettingModalPages/SettingModalAccount.tsx
> +						<div className="setting-desc-text-grey">{cyc_id && cyc_id}</div>
We need to change alot from the previous author for its efficiency, performance and readability anyways, 

Ok then i guess nullish coalescing works too  since were not doing any mathematical operations on it

2023-08-14 15:25 UTC, merged